# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3214ab90c78d2374ef422cd8414ffa90a200f420905cce31f1818e88c5dbe1062ec23a972074d1d5055d31afa2ed754fa04db120b5c3592a64cb664ce3ab1b7

test:
  secret_key_base: 14e5c1f05a1e6d62bf55a60cd59e6ff56f6bbeddcef22ef07f3ac51a11602f4c0ea91e828585245b90a2703f3a4aecae91114a9540980aee4439d41308de3ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
